# Generated by Django 2.1.4 on 2019-01-23 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_address_p2sh_p2wpkh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txid', models.CharField(max_length=128)),
                ('height', models.BigIntegerField(default=0)),
                ('timestamp', models.PositiveIntegerField(default=0)),
                ('value_in', models.BigIntegerField(default=0)),
                ('from_object', models.TextField(blank=True, null=True)),
                ('value_out', models.BigIntegerField(default=0)),
                ('to_object', models.TextField(blank=True, null=True)),
                ('fee', models.BigIntegerField(default=0)),
                ('value_unspent', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Address')),
            ],
        ),
    ]
