# Generated by Django 2.1.4 on 2019-01-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_remove_order_fee_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('cryptopair', models.CharField(default='', max_length=33)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('buy_fee', models.PositiveIntegerField(default=0)),
                ('sell_fee', models.PositiveIntegerField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order', to='order.Order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_order', to='order.Order')),
            ],
        ),
    ]
