# Generated by Django 2.1.4 on 2019-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='base_volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
