# Generated by Django 2.1.7 on 2019-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190224_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='settled',
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_order_settled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order_settled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
