# Generated by Django 2.1.7 on 2019-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190227_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='buy_order_settled',
            new_name='buy_order_settled_in',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='sell_order_settled',
            new_name='buy_order_settled_out',
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order_settled_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order_settled_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
