# Generated by Django 2.1.2 on 2018-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spauser', '0002_auto_20181022_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='spauser',
            name='passphrase',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
