# Generated by Django 2.1.2 on 2018-10-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spauser', '0003_spauser_passphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spauser',
            old_name='seed',
            new_name='salt',
        ),
    ]
