# Generated by Django 2.1.2 on 2018-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='seed',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wif',
            field=models.CharField(blank=True, max_length=51),
        ),
    ]
