# Generated by Django 2.1.2 on 2018-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20181021_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='seed',
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wif',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
