# Generated by Django 2.1.2 on 2018-10-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_last_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='last_index',
            new_name='last_change_index',
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_external_index',
            field=models.IntegerField(default=0),
        ),
    ]
