# Generated by Django 2.1.2 on 2018-10-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20181022_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='wif',
        ),
    ]
