# Generated by Django 2.1.2 on 2018-10-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='is_change',
            field=models.BooleanField(default=False),
        ),
    ]
