# Generated by Django 2.1.2 on 2018-10-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20181022_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='passphrase',
        ),
        migrations.RemoveField(
            model_name='address',
            name='secret_exponent',
        ),
        migrations.RemoveField(
            model_name='address',
            name='wif',
        ),
    ]
