# Generated by Django 2.1.7 on 2019-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_p2sh_p2wpkh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='bech32',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='p2pkh',
            field=models.CharField(db_index=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='p2sh_p2wpkh',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
