# Generated by Django 2.1.2 on 2019-01-02 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0006_remove_wallet_wif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cryptopair', models.CharField(max_length=32)),
                ('side', models.BooleanField(default=False)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('original_volume', models.PositiveIntegerField(default=0)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('fee_currency', models.CharField(max_length=16)),
                ('timeinforce', models.CharField(default='GTC', max_length=3)),
                ('open', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('filled', models.PositiveIntegerField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet')),
            ],
        ),
    ]
