# Generated by Django 2.1.2 on 2019-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeinforce',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
