# Generated by Django 2.1.2 on 2019-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190102_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_currency',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_currency',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='cryptopair',
            field=models.CharField(default='', max_length=33),
        ),
    ]
