# Generated by Django 2.1.2 on 2019-01-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190102_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='limit',
            new_name='limit_price',
        ),
    ]
