# Generated by Django 2.1.4 on 2019-01-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190103_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee_currency',
        ),
    ]
