# Generated by Django 2.1.4 on 2019-01-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_fee_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='settled',
        ),
    ]
