# Generated by Django 2.1.4 on 2019-02-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timeinforce',
        ),
        migrations.AddField(
            model_name='order',
            name='timeinforce',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

